[theme]

# Primary accent for interactive elements
primaryColor = '#e3345a'

# Background color for the main content area
backgroundColor = '#567EA6'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor="#4f4d4e"

# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "sans serif"
